site:
  language: en
  title: "cécile ricordeau"
  baseline: "creative and art director"
  baseurl: https://www.cecillie.fr/
  description: "Cécile Ricordeau, Creative Director"
  links:
    Behance: https://www.behance.net/cecillie
    Vimeo: https://vimeo.com/cecillie
    Linkedin: https://www.linkedin.com/in/digitalcreation/
    Twitter: https://www.twitter.com/onibd
    CV: cecile-ricordeau-cv.pdf
    Contact: mailto:cecile.ricordeau@gmail.fr
  author:
    name: Cécile Ricordeau
    url: https://www.cecillie.fr
