title: "cécile ricordeau"
baseurl: https://www.cecillie.fr/
baseline: "Creative and Art direction, UI and UX design"
description: "Cécile Ricordeau, freelance creative and art director in paris, ui and ux designer, specialized in creative strategy and conception."
language: en
links:
  Behance: https://www.behance.net/cecillie
  Vimeo: https://vimeo.com/cecillie
  Linkedin: https://www.linkedin.com/in/digitalcreation/
  Twitter: https://www.twitter.com/onibd
  Medium: https://medium.com/@cecile.ricordeau
  Book: http://bitly.com/cecillie
  CV: cecile-ricordeau-cv.pdf
  hello[at]cecillie.fr: mailto:hello@cecillie.fr
author:
  name: "Cécile Ricordeau"
  url: https://www.cecillie.fr
