site:
  title: "cécile ricordeau"
  baseurl: https://www.cecillie.fr/
  baseline: "creative and art direction"
  description: "Cécile Ricordeau, freelance creative and art director in paris, specialized in creative strategy and conception."
  language: en-us
  links:
    Behance: https://www.behance.net/cecillie
    Vimeo: https://vimeo.com/cecillie
    Linkedin: https://www.linkedin.com/in/digitalcreation/
    Twitter: https://www.twitter.com/onibd
    Medium: https://medium.com/@cecile.ricordeau
    CV: cecile-ricordeau-cv.pdf
    hello[at]cecillie.fr: mailto:hello@cecillie.fr
  author:
    name: "Cécile Ricordeau"
    url: https://www.cecillie.fr
