site:
  title: "cécile ricordeau"
  baseurl: https://www.cecillie.fr/
  baseline: "creative and art director"
  description: "i'm cécile, a creative and art director in paris. i specialize in creative strategy and believe in the power of a good and human creative process."
  language: en
  links:
    Behance: https://www.behance.net/cecillie
    Vimeo: https://vimeo.com/cecillie
    Linkedin: https://www.linkedin.com/in/digitalcreation/
    Twitter: https://www.twitter.com/onibd
    CV: cecile-ricordeau-cv.pdf
    Contact: mailto:cecile.ricordeau@gmail.com
  author:
    name: "Cécile Ricordeau"
    url: https://www.cecillie.fr
